version: '3.2'
services:
  db:
    image: postgres
    environment:
      PGDATA: "/var/lib/postgresql/data/rentme"
    volumes:
      - "database:/var/lib/postgresql/data/rentme"
  taskqueue:
    image: rabbitmq:management
  django:
    build:
      context: .
      dockerfile: django.Dockerfile
    volumes:
      - "www:/var/www"
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
  django-init:
    build:
      context: .
      dockerfile: django.Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: 'rentme.settings'
    command: ["--root", "/post-install.sh"]
    volumes:
      - "www:/var/www"
      - .:/code
    links:
      - db
  celery:
    build:
      context: .
      dockerfile: celery.Dockerfile
    volumes:
      - .:/code
    links:
      - db
      - taskqueue
  flower:
    build:
      context: .
      dockerfile: flower.Dockerfile
    volumes:
      - .:/code
      - /flower-db
    ports:
      - "5555:5555"
    links:
      - db
      - taskqueue
volumes:
  database:
  www:
