# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliable_viewing_times', models.ManyToManyField(to='raw.ViewingTime')),
            ],
        ),
    ]
