# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0002_auto_20170610_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaldata',
            name='bullet_points',
        ),
        migrations.DeleteModel(
            name='AdditionalDataBulletPoints',
        ),
        migrations.AlterUniqueTogether(
            name='attribute0',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='attribute0',
            name='options',
        ),
        migrations.RemoveField(
            model_name='attribute0',
            name='range',
        ),
        migrations.RemoveField(
            model_name='attribute0',
            name='units',
        ),
        migrations.DeleteModel(
            name='AttributeOption0',
        ),
        migrations.DeleteModel(
            name='AttributeUnit',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='DraftListingResponse',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='SimpleGeographicLocation',
        ),
        migrations.DeleteModel(
            name='TmShippingCalculatorInputs',
        ),
        migrations.DeleteModel(
            name='AdditionalData',
        ),
        migrations.DeleteModel(
            name='Attribute0',
        ),
    ]
