# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0003_auto_20170616_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleMemberProfile',
        ),
        migrations.RemoveField(
            model_name='store',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='listeditemdetail',
            name='member_profile',
            field=models.ForeignKey(blank=True, help_text='This listing member’s public profile information.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listed_item_detail_reverse_member_profile', to='raw.MemberProfile'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Basic information about the member.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to='raw.Member'),
        ),
    ]
