# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('kwargs', models.TextField()),
                ('content', models.BinaryField()),
                ('data', models.TextField()),
                ('expiry', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cachedresponse',
            unique_together=set([('method', 'url', 'kwargs')]),
        ),
    ]
