# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agency',
            table=None,
        ),
        migrations.AlterModelTable(
            name='agencyagent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='attributes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='broadbandtechnology',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='district',
            table=None,
        ),
        migrations.AlterModelTable(
            name='geographiclocation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='listing',
            table=None,
        ),
        migrations.AlterModelTable(
            name='locality',
            table=None,
        ),
        migrations.AlterModelTable(
            name='member',
            table=None,
        ),
        migrations.AlterModelTable(
            name='membershipdistrict',
            table=None,
        ),
        migrations.AlterModelTable(
            name='membershiplocality',
            table=None,
        ),
        migrations.AlterModelTable(
            name='photo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='suburb',
            table=None,
        ),
    ]
