# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial_squashed_0002_auto_20170401_1004_squashed_0007_auto_20170616_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='locality',
            field=models.ForeignKey(help_text='The list of districts that belong to this region.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='data.Locality'),
        ),
        migrations.AlterField(
            model_name='membershipdistrict',
            name='locality',
            field=models.ForeignKey(help_text='The list of districts that belong to this region.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='data.MembershipLocality'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='district',
            field=models.ForeignKey(help_text='The list of suburbs that belong to this district.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suburbs', to='data.District'),
        ),
    ]
