# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial_squashed_0002_auto_20170401_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_photo_set', to='data.Photo'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
