# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20170622_1142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agency',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set([]),
        ),
    ]
