# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20170402_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='broadbandtechnology',
            options={'ordering': ['max_down', 'max_up', 'name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['nickname', 'member_id']},
        ),
        migrations.AlterModelOptions(
            name='membershipdistrict',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='membershiplocality',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['photo_id']},
        ),
        migrations.AlterModelOptions(
            name='suburb',
            options={'ordering': ['name']},
        ),
    ]
