# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170622_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='member_profile',
        ),
        migrations.AddField(
            model_name='agent',
            name='agency',
            field=models.ManyToManyField(help_text='The agency that this agent is contactable at.', related_name='agents', to='data.Agency'),
        ),
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.TextField(help_text='The address to display.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='biography',
            field=models.TextField(help_text='The member’s bio.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_removed',
            field=models.DateTimeField(help_text='The date the member was disabled (assuming it has been disabled).', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='favourite_id',
            field=models.IntegerField(help_text='The ID of a favourite seller, if the call is authenticated and this member is a favourite seller for the authenticated caller.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.TextField(help_text='The first name of the member.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_enabled',
            field=models.NullBooleanField(help_text='Indicates whether the member account is enabled.'),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.TextField(help_text='The occupation of the member.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='quote',
            field=models.TextField(help_text='The member’s favourite quote.', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.TextField(help_text='A URL representing the member’s photo.', null=True),
        ),
        migrations.DeleteModel(
            name='SimpleMemberProfile',
        ),
    ]
