# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rentme.data.models._utils
import trademe.models.enums


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20170518_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuburbAdjacentSuburbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agencyagent',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='broadband_technologies',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='geographic_location',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='member',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='suburb',
        ),
        migrations.AddField(
            model_name='category',
            name='can_be_second_category',
            field=models.NullBooleanField(help_text='Indicates whether this category can be selected as a second category.'),
        ),
        migrations.AddField(
            model_name='category',
            name='can_have_second_category',
            field=models.NullBooleanField(help_text='Indicates whether this category can be paired with a second category.'),
        ),
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(help_text='The number of items for sale in this category.', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='area_of_business',
            field=rentme.data.models._utils.EnumIntegerField(enum=trademe.models.enums.AreaOfBusiness, help_text='Area of business this category is related to', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='has_classifieds',
            field=models.NullBooleanField(help_text='Indicates whether classifieds are allowed in this category.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='has_legal_notice',
            field=models.NullBooleanField(help_text='Indicates whether the category has legal requirements. You should ask the user to accept the legal notice before listing in this category. There is an API to get the text of the legal notice.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_restricted',
            field=models.NullBooleanField(help_text='Indicates whether the category is restricted to adults only (i.e. the category is R18).'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(help_text='The name of the category.', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.TextField(help_text='A unique identifier for the category e.g. “0004-0369-6076-“. We plan to change this to a numeric identifier (e.g. “6076”) so you should ensure you can cope with both formats.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(help_text='The list of subcategories belonging to this category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='data.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.TextField(help_text='The full URL path of this category e.g. “/Home-living/Beds-bedroom-furniture/Bedside-tables”.', null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_id',
            field=models.IntegerField(help_text='The ID of the district.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='locality',
            field=models.ForeignKey(help_text='The list of districts that belong to this region.', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='data.Locality'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.TextField(help_text='The name of the district.', null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='locality_id',
            field=models.IntegerField(help_text='The ID of the region.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.TextField(help_text='The name of the region.', null=True),
        ),
        migrations.AlterField(
            model_name='membershipdistrict',
            name='district_id',
            field=models.IntegerField(help_text='The ID of the district.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membershipdistrict',
            name='locality',
            field=models.ForeignKey(help_text='The list of districts that belong to this region.', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='data.MembershipLocality'),
        ),
        migrations.AlterField(
            model_name='membershipdistrict',
            name='name',
            field=models.TextField(help_text='The name of the district.', null=True),
        ),
        migrations.AlterField(
            model_name='membershiplocality',
            name='locality_id',
            field=models.IntegerField(help_text='The ID of the region.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membershiplocality',
            name='name',
            field=models.TextField(help_text='The name of the region.', null=True),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='district',
            field=models.ForeignKey(help_text='The list of suburbs that belong to this district.', on_delete=django.db.models.deletion.CASCADE, related_name='suburbs', to='data.District'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='name',
            field=models.TextField(help_text='The name of the suburb.', null=True),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='suburb_id',
            field=models.IntegerField(help_text='The ID of the suburb.', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='AgencyAgent',
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
        migrations.DeleteModel(
            name='BroadbandTechnology',
        ),
        migrations.DeleteModel(
            name='GeographicLocation',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='ListingPrice',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterUniqueTogether(
            name='suburbadjacentsuburbs',
            unique_together=set([('value',)]),
        ),
        migrations.AddField(
            model_name='suburb',
            name='adjacent_suburbs_ids',
            field=models.ManyToManyField(help_text='A list containing the IDs of the suburbs adjacent to this suburb.', related_name='suburb_reverse_adjacent_suburbs', to='data.SuburbAdjacentSuburbs'),
        ),
    ]
