# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20170630_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='suburb',
        ),
        migrations.AddField(
            model_name='listing',
            name='suburb',
            field=models.ForeignKey(blank=True, help_text='The suburb where this item is located.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='data.Suburb'),
        ),
    ]
