# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20170630_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agency',
        ),
        migrations.AddField(
            model_name='agent',
            name='agency',
            field=models.ForeignKey(help_text='The agency that this agent is contactable at.', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='data.Agency'),
        ),
    ]
