# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20170630_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='The agency details if this is a job or property listing.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listed_item_detail_reverse_agency', to='data.Agency'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='embedded_content',
            field=models.ForeignKey(blank=True, help_text='The content keys that are embedded in the listing page (e.g. YouTube Video Key).', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.EmbeddedContent'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='geographic_location',
            field=models.ForeignKey(blank=True, help_text='The geographic location (latitude and longitude) of a property.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.GeographicLocation'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='member',
            field=models.ForeignKey(blank=True, help_text='The seller of the listing.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Member'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ForeignKey(help_text='A collection of photos for the listing.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.Photo'),
        ),
    ]
