# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TraceMeAgencyAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('position', models.TextField(null=True)),
                ('mobile_number', models.CharField(max_length=20, null=True)),
                ('office_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fax_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeMeAgency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('website', models.URLField(null=True)),
                ('logo', models.URLField(null=True)),
                ('is_real_estate_agency', models.BooleanField()),
                ('is_licensed_property_agency', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeMeListing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('available_from', models.TextField(null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('rent_per_week', models.IntegerField()),
                ('category', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('generated_at', models.DateTimeField()),
                ('stored_at', models.DateTimeField(auto_now=True)),
                ('thumbnail_href', models.URLField(null=True)),
                ('agency', models.ManyToManyField(to='web.TradeMeAgency')),
            ],
        ),
        migrations.CreateModel(
            name='TradeMeListingAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
                ('value', models.TextField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='web.TradeMeListing')),
            ],
        ),
        migrations.CreateModel(
            name='TradeMeListingLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('accuracy', models.IntegerField(choices=[(0, 'None'), (1, 'Address'), (3, 'Street'), (2, 'Suburb')])),
            ],
        ),
        migrations.CreateModel(
            name='TradeMeListingPhoto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('thumbnail', models.URLField(null=True)),
                ('list', models.URLField(null=True)),
                ('medium', models.URLField(null=True)),
                ('gallery', models.URLField(null=True)),
                ('large', models.URLField(null=True)),
                ('full_size', models.URLField(null=True)),
                ('plus_size', models.URLField(null=True)),
                ('original_width', models.IntegerField()),
                ('original_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeMeMember',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('suburb', models.TextField()),
                ('region', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='trademelistinglocation',
            unique_together=set([('latitude', 'longitude', 'accuracy')]),
        ),
        migrations.AddField(
            model_name='trademelisting',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TradeMeListingLocation'),
        ),
        migrations.AddField(
            model_name='trademelisting',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.TradeMeMember'),
        ),
        migrations.AddField(
            model_name='trademelisting',
            name='photos',
            field=models.ManyToManyField(to='web.TradeMeListingPhoto'),
        ),
        migrations.AddField(
            model_name='tracemeagencyagent',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='web.TradeMeAgency'),
        ),
        migrations.AddField(
            model_name='propertyreview',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='web.TradeMeListing'),
        ),
        migrations.AlterUniqueTogether(
            name='trademelistingattribute',
            unique_together=set([('listing', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='tracemeagencyagent',
            unique_together=set([('agency', 'full_name')]),
        ),
    ]
