# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rentme.web.models._utils
import trademe.models.enums


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.TextField()),
                ('number', models.TextField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('is_restricted', models.BooleanField()),
                ('has_legal_notice', models.BooleanField()),
                ('has_classifieds', models.BooleanField()),
                ('area_of_business', rentme.web.models._utils.EnumIntegerField(enum=trademe.models.enums.AreaOfBusiness)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='web.Category')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipDistrict',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipLocality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('adjacent_suburbs', models.ManyToManyField(related_name='_suburb_adjacent_suburbs_+', to='web.Suburb')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suburbs', to='web.District')),
            ],
        ),
        migrations.RemoveField(
            model_name='propertyreview',
            name='property',
        ),
        migrations.AlterUniqueTogether(
            name='tracemeagencyagent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tracemeagencyagent',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='trademelisting',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='trademelisting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trademelisting',
            name='member',
        ),
        migrations.RemoveField(
            model_name='trademelisting',
            name='photos',
        ),
        migrations.AlterUniqueTogether(
            name='trademelistingattribute',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='trademelistingattribute',
            name='listing',
        ),
        migrations.DeleteModel(
            name='TradeMeListingLocation',
        ),
        migrations.DeleteModel(
            name='PropertyReview',
        ),
        migrations.DeleteModel(
            name='TraceMeAgencyAgent',
        ),
        migrations.DeleteModel(
            name='TradeMeAgency',
        ),
        migrations.DeleteModel(
            name='TradeMeListing',
        ),
        migrations.DeleteModel(
            name='TradeMeListingAttribute',
        ),
        migrations.DeleteModel(
            name='TradeMeListingPhoto',
        ),
        migrations.DeleteModel(
            name='TradeMeMember',
        ),
        migrations.AddField(
            model_name='membershipdistrict',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='web.MembershipLocality'),
        ),
        migrations.AddField(
            model_name='district',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='web.Locality'),
        ),
    ]
