# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20161203_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='has_classifieds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='has_legal_notice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
