# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 11:18
from __future__ import unicode_literals

from django.db import migrations
import rentme.web.models._utils
import trademe.models.enums


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20161203_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='area_of_business',
            field=rentme.web.models._utils.EnumIntegerField(enum=trademe.models.enums.AreaOfBusiness, null=True),
        ),
    ]
