# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20161203_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='listrict_id',
            new_name='district_id',
        ),
    ]
