# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rentme.web.models._utils
import api.trademe.enums


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20161204_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('branding_background_color', models.TextField()),
                ('branding_large_banner_url', models.TextField()),
                ('branding_office_location', models.TextField()),
                ('branding_stroke_color', models.TextField()),
                ('branding_text_color', models.TextField()),
                ('fax_number', models.TextField(blank=True)),
                ('is_licensed_property_agency', models.BooleanField()),
                ('is_real_estate_agency', models.BooleanField()),
                ('logo', models.URLField(blank=True, null=True)),
                ('logo2', models.URLField(blank=True, null=True)),
                ('name', models.TextField(blank=True)),
                ('phone_number', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('mobile_phone_number', models.TextField(blank=True)),
                ('office_phone_number', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('display_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BroadbandTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('completion', models.TextField()),
                ('availability', models.TextField()),
                ('min_down', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('max_down', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('min_up', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('max_up', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='GeographicLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', rentme.web.models._utils.EnumIntegerField(enum=api.trademe.enums.GeographicLocationAccuracy)),
                ('easting', models.IntegerField()),
                ('northing', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('allows_pickups', models.BooleanField()),
                ('as_at', models.DateTimeField()),
                ('bidder_and_watchers', models.IntegerField()),
                ('body', models.TextField(blank=True)),
                ('can_add_to_cart', models.BooleanField()),
                ('end_date', models.DateTimeField()),
                ('has_gallery', models.BooleanField()),
                ('is_bold', models.BooleanField()),
                ('is_classified', models.BooleanField()),
                ('is_featured', models.BooleanField()),
                ('is_highlighted', models.BooleanField()),
                ('is_super_featured', models.BooleanField()),
                ('note_date', models.DateTimeField()),
                ('price_display', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('super_feature_end_date', models.DateTimeField()),
                ('title', models.TextField()),
                ('view_count', models.BooleanField()),
                ('viewing_tracker_supported', models.BooleanField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='web.Agency')),
                ('attributes', models.ManyToManyField(related_name='listings', to='web.Attributes')),
                ('broadband_technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='web.BroadbandTechnology')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='web.Category')),
                ('geographic_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='web.GeographicLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('unique_positive', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('is_authenticated', models.BooleanField()),
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('unique_negative', models.IntegerField()),
                ('feedback_count', models.IntegerField()),
                ('region', models.TextField()),
                ('suburb', models.TextField()),
                ('is_address_verified', models.BooleanField()),
                ('date_address_verified', models.DateTimeField()),
                ('photo', models.URLField()),
                ('original_width', models.IntegerField(default=-1)),
                ('original_height', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('thumbnail', models.URLField()),
                ('list', models.URLField()),
                ('medium', models.URLField()),
                ('gallery', models.URLField()),
                ('large', models.URLField()),
                ('full_size', models.URLField()),
                ('plus_size', models.URLField()),
                ('original_width', models.IntegerField(default=-1)),
                ('original_height', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='web.Member'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Photo'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photos',
            field=models.ManyToManyField(related_name='listings', to='web.Photo'),
        ),
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.ManyToManyField(related_name='listings', to='web.Locality'),
        ),
        migrations.AddField(
            model_name='listing',
            name='suburb',
            field=models.ManyToManyField(related_name='listings', to='web.Suburb'),
        ),
        migrations.AddField(
            model_name='agency',
            name='agents',
            field=models.ManyToManyField(to='web.AgencyAgent'),
        ),
    ]
