# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170130_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='broadband_technologies',
        ),
        migrations.AddField(
            model_name='listing',
            name='broadband_technologies',
            field=models.ManyToManyField(related_name='listings', to='web.BroadbandTechnology'),
        ),
    ]
