# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170130_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='region',
        ),
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='web.Locality'),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='suburb',
        ),
        migrations.AddField(
            model_name='listing',
            name='suburb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='web.Suburb'),
        ),
    ]
