# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170130_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='web.Locality'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='web.Suburb'),
        ),
    ]
