# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20170130_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='view_count',
            field=models.IntegerField(),
        ),
    ]
