# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20170130_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Photo'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='viewing_tracker_supported',
            field=models.BooleanField(default=False),
        ),
    ]
