# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20170130_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agents',
        ),
        migrations.AddField(
            model_name='agencyagent',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='web.Agency'),
        ),
    ]
