# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20170130_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='is_licensed_property_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agency',
            name='is_real_estate_agency',
            field=models.BooleanField(default=False),
        ),
    ]
