# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_remove_listing_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.TextField(blank=True),
        ),
    ]
