# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20170130_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_super_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='super_feature_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
