# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20170211_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='has_gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_classified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
