# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20170211_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='branding_disable_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencyagent',
            name='url_slug',
            field=models.TextField(blank=True),
        ),
    ]
